"""user table

Revision ID: 6db9a4ec11ce
Revises: 2803e49d8744
Create Date: 2021-05-14 00:00:25.124442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db9a4ec11ce'
down_revision = '2803e49d8744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'progress')
    # ### end Alembic commands ###
