"""user table

Revision ID: de02f15dc792
Revises: 2803e49d8744
Create Date: 2021-05-13 23:38:58.981951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de02f15dc792'
down_revision = '2803e49d8744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'progress')
    # ### end Alembic commands ###
