"""user table

Revision ID: ffddd0679dad
Revises: 6db9a4ec11ce
Create Date: 2021-05-14 00:25:32.822482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffddd0679dad'
down_revision = '6db9a4ec11ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testScore')
    # ### end Alembic commands ###
